### PR TITLE
Guzzle 6.0 support

### PR DESCRIPTION
**Pull request by mpatnode-si**
The changes are pretty simple.   Someone still needs to bump the version number & Guzzle dependency.  Not sure how that works.

### CODE REVIEW

**Comment by paulli** [comment]
Thanks for the pull request. The tests are failing after the Guzzle 6 upgrade. Could you fix that also please?

**Comment by mpatnode-si** [comment]
Took a run at the unit test.  No clue what you're trying to do with History there.   Someone smarter than me will need to take a run at it.

**Comment by BenWise9000** [comment]
@mpatnode-si I've sent a pull request from my repo for this one that has working Unit tests for Guzzle 6. Guzzle 6 support means PHP >=5.5 is required.

**Comment by kkopachev** [comment]
@paulli This PR is good for another look.

**Comment by mpatnode-si** [comment]
:+1:

**Comment by richzertuche** [comment]
Was this pull request ever merged?

Thanks

**Comment by k4hoo** [comment]
@mpatnode-si, @BenWise9000 , @kkopachev  Thanks for your contribution! We would like to merge this PR. Would you sign the contributor CLA form https://prediction.io/cla/ ?   Thanks!

**Comment by kkopachev** [comment]
done

**Comment by jaumebosch** [comment]
@BenWise9000 @mpatnode-si Come on guys! we need you agreement to merge this!

**Comment by mpatnode-si** [comment]
I signed my when I saw the email.   Did it not work?

mp

**Comment by jaumebosch** [comment]
will ask to @k4hoo,

Thanks!

**Comment by k4hoo** [comment]
Thanks @mpatnode-si  and @kkopachev ! you guys are OK.

@BenWise9000 would you get a chance to sign the CLA? this PR has a great demand and would benefit the community a lot, but I can't merge it until all contributors have singed the [CLA]( https://prediction.io/cla/). Thanks!

**Comment by BenWise9000** [comment]
@k4hoo Mine is signed now too. Thanks!

**Comment by k4hoo** [comment]
Thanks @BenWise9000 !

**Comment by jaumebosch** [comment]
cool!
When it will be merged in the master branch  @k4hoo ?

**Comment by k4hoo** [comment]
@jaumebosch  PHP SDK 0.9.0 is released. please try and see if it works. thanks!

**Comment by jaumebosch** [comment]
updated and testing.

will inform

**Pull request merged**
